### ISSUE TITLE
[COMPONENT] - Navbar

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-webapp#2]
Create a navigation top bar component for the webapp (see the mockup in the readme).

@harsimrat99 Feel free to populate this with more specifics of what you would like.

**Comment by harsimrat99** [comment]
@JLefebvre55 Thank you for creating these issues. @iWebster28 please let me know if there are any concerns regarding the setup of the repository or for running tests.

**Comment by JLefebvre55** [comment]
@harsimrat99 Looks good for a first draft. Close this issue?

**Comment by iWebster28** [comment]
Completed
