### ISSUE TITLE
[BUG] - CORS for Backend API Access

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-webapp#5]
The backend API and the webapp are currently hosted in two different repositories, and thus run on two different processes and bind to two different ports. As such, we need to implement **cross-origin resource sharing** to allow requests to be made.

Maybe @CloudClub-uoft/backend should tackle this?

**Comment by JLefebvre55** [comment]
There might be a way to do this via Express.

**Comment by harsimrat99** [comment]
https://expressjs.com/en/resources/middleware/cors.html

Typical CORS package. Allows for XHRs to succeed when using React frontends.

**Comment by iWebster28** [comment]
fyi, current plugin that I'm using to get around this issue (while hosting backend on pi): https://www.moesif.com/blog/technical/cors/Authoritative-Guide-to-CORS-Cross-Origin-Resource-Sharing-for-REST-APIs/

**Comment by matt8100** [comment]
I've created a [branch for this in the backend repo](https://github.com/CloudClub-uoft/iot-device-backend/tree/matt8100-cors). Can you let me know how I should go about testing this? I am unable to get the `api-fetch` branch to run.

**Comment by JLefebvre55** [comment]
> Can you let me know how I should go about testing this? I am unable to get the `api-fetch` branch to run.

@iWebster28 wondering if you've got `api_fetch` running?

As far as testing goes, clone the backend repo and launch the server one one port, then clone and run (`npm start`) this repo. If you're able to make cross-origin requests, then we're in business

**Comment by iWebster28** [comment]
Previous Setup:
1. Raspberry Pi running backend
2. Desktop running frontend
3. CORS extension running in browser for frontend

Previous Expectation:
- Clicking the "Get API Key" button should fetch a test api key from the server (see Register.js for the temporary POST request - this will be changed later)
- Open your browser inspector to see the logged api_key

**Comment by iWebster28** [comment]
See latest commit for frontend. 38b659e31b26390e9df8151e3a6d598fe6558728

Current Setup
1. Frontend/backend on same machine
2. CORS extension

Current Expectation:
- Should be able to fetch from backend **without** CORS extension enabled

Actual:
- CORS extension must be **on** for fetch to work

**Comment by iWebster28** [comment]
Latest commit allows you to test with a Device ID and Friendly Name. c07a63c1c8dd9243a389743d5a4261aa2ba880e6

![image](https://user-images.githubusercontent.com/26224804/125723521-91fd9bea-716b-4ae5-b1a6-292eb68e8cc9.png)

**Comment by iWebster28** [comment]
Okay, this worked. Latest frontend commit changes some ports. 3319323
